name: BCModel
channels: 
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipython
  - notebook=6.5
  - jupyterlab
  - pip=23.2.1
  - mesa=3.1.3
  - seaborn=0.13.2
  - pip:
    - networkx==2.6.2
    - pyabc
    - rise